### ISSUE TITLE
Audio Jack Output?

### ISSUE THREAD

**Issue by AGenews** [open-ephys/acquisition-board#10]
Hi there,
I thought I could feed the signal of one recorded channel in 'real-time' over the audio jack on the acquisition board to a window discriminator and do some collision experiments. But unfortunately I only have some maybe 250 kHz @ 20 mV noise there. So no modulation regardless whats going on on the channel. My board is made from the plans of January 2014 and I am using the 0.34 GUI. Any help?
Best,
Andreas

**Comment by AGenews** [comment]
Ok it seems to work somehow after I reloaded everything, however I can see something which might be called field potentials (+/- 100mV on the scope) but no chance for spikes at all. I use an active filter device. However I can see nice spikes in the GUI. And I know that those are spikes as I can turn them off with archaerhosopsin ;)

**Comment by jsiegle** [comment]
I'm not sure what's going on here. The analog output should replicate the exact signal that's being sent to the GUI. Do both output channels 1 & 2 look similar? What are the details of your active filter device?

If you have an earlier version of the board, the LEDs can interfere with the audio output—that could explain why the noise went away after a restart.

**Comment by AGenews** [comment]
As it is the first time that i use this feature on my board, I'll measure everything through and check whether there are some shorts or loose contacts. I keep you posted.
Best,
Andreas
