### ISSUE TITLE
Can we add digital inputs to 16 channel?

### ISSUE THREAD

**Issue by liyipeng-moon** [open-ephys/acquisition-board#19]
Hi everyone, My experiment needs more than 256 event code, so I want to add the number of digital input channels to 16. Could you please give me any advice? Thank you!

**Comment by liyipeng-moon** [comment]
more 8 channels is available on the at the bottom of board. Sorry to bother everyone：）

**Comment by aacuevas** [comment]
Keep in mind that those channels at the bottom of the board do not have any level translation and are connected directly to the FPGA.
Thus, you must not connect there any voltage higher than 3.3V, or the FPGA will be damaged.

**Comment by cxrodgers** [comment]
It seems to me you could also transmit two event codes per event, giving you 256 * 256 distinct codes with the same number of channels. Just a thought

**Comment by liyipeng-moon** [comment]
> Keep in mind that those channels at the bottom of the board do not have any level translation and are connected directly to the FPGA. Thus, you must not connect there any voltage higher than 3.3V, or the FPGA will be damaged.

Thank you aacuevas! I think I should add a level translator before connecting digital port to OE board

**Comment by liyipeng-moon** [comment]
> It seems to me you could also transmit two event codes per event, giving you 256 * 256 distinct codes with the same number of channels. Just a thought

Thank you! this is also a solution worth trying!
