### ISSUE TITLE
Impedance testing reports 1kOhm with open 32ch Intan headstage

### ISSUE THREAD

**Issue by musall** [open-ephys/acquisition-board#25]
Hi all,

we are using the impedance test feature to check the status of our probes before implantation. This works well with the 16-channel Intan head stage and reports 20-30 MOhm in open circuit and ranges in the kOhm range when a probe is connected.
However, when using the 32-channel Intan head stage,  all impedance measures are around 1kOhm and don't change any further when connecting a probe. When putting a contact on ground the impedance falls to about 400 Ohms but there seems to be a problem with correctly detecting higher impedance.

Is there anything we can do about this? Is there a setting to change from the 16 to the 32 channel headstage for the impedance test to work correctly?

Thank you and best regards,
Simon

**Comment by jsiegle** [comment]
I'm not sure what could explain the difference – both headstages use the same chip, the 16 channel version just has half the channels connected.

Is the problem replicable across multiple 32 channel headstages, or do you only have one?

Also, are you using the "Acquisition Board" plugin (using the Opal Kelly FPGA) or the "OE FPGA Acquisition Board" plugin?

**Comment by musall** [comment]
I'm also confused about the difference - perhaps there is something wrong with the 32-channel headstage. We currently have only one and the recorded signals look OK but knowing that there is nothing to change on the software side is already helpful. The board is the Opal Kelly FPGA (using Acquisition Board v2.2).
Thank you for the quick response!

**Comment by jsiegle** [comment]
Yeah, there shouldn't be any software change that's needed. I just tested a 32-channel headstage with the Opal Kelly-based acquisition board and the impedance values looked reasonable. So it's probably an issue with that specific headstage.

**Comment by musall** [comment]
I also borrowed another headstage and got much better results, so can confirm it's an issue with that specific part. I'm surprised that it seems to acquire regular physiological signals but we should probably replace it.
Thanks again for the help and testing the headstage on your end!

**Comment by musall** [comment]
Closing the issue again
